### ISSUE TITLE
How should episode ordering work

### ISSUE THREAD

**Issue by sandikbarr** [PRX/cms.prx.org#165]
Is it based on a position, the published at? What happens to the order when stories are republished? How does the order on PRX translate to the order on the RSS feed?

**Comment by cavis** [comment]
Just noticed this in @kookster's latest PR...

Outside the context of series, it's usually published_at.  Or modified_at, if looking at your unpublished stories.

In the context of `series/stories`, they're ordered by `episode_number DESC, position DESC, published_at DESC`.  So if you're using episode number or position, that will explicitly set the order.  Otherwise, falls back to publish.

"Republishing" is a bit of a misnomer.  The normal workflow would be to just make save changes to the already-published story, without touching the publishedAt date.  So you'd end up with `updatedAt > publishedAt`.  And feeder should pick up that change, without impacting the order of the episodes.

The only way to change the published date would be to explicitly click the "Unpublish" button (setting it back to nil), then clicking "Publish" again.  Not sure that would/should ever be part of a normal workflow.

**Comment by kookster** [comment]
Yeah, we might need to keep some kind of last published or first published at value if we start having publish and unpublish happening alot for v4 stories, idk.

**Comment by kookster** [comment]
decision: published_at all the way

allow to update and save while published, validations will not prevent, so should not need to unpublish and reset published_at date.
