### ISSUE TITLE
_embedded prx:stories different from _links prx:stories

### ISSUE THREAD

**Issue by gcampo88** [PRX/cms.prx.org#215]
Api::SeriesRepresenter embeds stories using :public_stories: 
```ruby
  embed :public_stories,
        as: :stories,
        paged: true,
        item_class: Story,
        item_decorator: Api::Min::StoryRepresenter
```
And that should then get overwritten by Api::Auth::SeriesRepresenter: 
```ruby
embed :stories,
        paged: true,
        item_class: Story,
        item_decorator: Api::Auth::StoryMinRepresenter,
        url: ->(_r) { api_authorization_series_stories_path(represented.parent) },
        zoom: false
```

But it looks like the `embed :stories` override is not happening (though the `link :stories` seems to be working fine). 
Screenshot from a series doc in publish-- _embedded stories show the 4 public stories in series (non-authorized access to stories) and _links shows the authorization link to the stories, with count of 12 (including the 4 public plus the 8 private stories). 

![screen shot 2017-01-05 at 5 57 29 pm](https://cloud.githubusercontent.com/assets/16007382/21700854/72b763aa-d370-11e6-84cc-d6e5f9a9f239.png)

Looks like there are no Auth Series Representer tests, so could make sense to add one for this case. 
@kookster is this an accurate summary?

**Comment by kookster** [comment]
accurate!

**Comment by kookster** [comment]
@gcampo88 wanna try fixing this one?

You can try fiddling with the embed method code to see if you can figure out why the auth representer isn't overriding the `embed :stories`, but I think the fix is to stop inheriting the SeriesRepresenter in the Auth::SeriesRepresenter, and instead copy over the desired properties/links to this one.

Nothing strictly wrong with that - our Min representers work the same way.
I am increasingly coming to the conclusion that inheriting representers just may be a bad idea (I have had to undo such inheritance to fix bugs a couple of times now already).

**Comment by kookster** [comment]
fixed!
